### ISSUE TITLE
How to trace an executed workflow?

### ISSUE THREAD

**Issue by macgyver2k** [wasabii/Cogito.ServiceFabric#2]
I am executing XAML Workflows inside the ActivityActor. When a workflow fails, I would like to access the trace of the whole workflow.

In my Tests for the Workflows, I use the WorkflowTestApplication class from [Microsoft.Activities.UnitTesting](https://www.nuget.org/packages/Microsoft.Activities.UnitTesting)

calling `this.WorkflowApplicationTest.Tracking.Trace();` outputs the following (shortened):

`7: Activity [1.60] "Flowchart" scheduled child activity [1.2542] "WaitForInitializeInput"`
`8: Activity [1.2542] "WaitForInitializeInput" is Executing`
`9: Activity [1.2542] "WaitForInitializeInput" scheduled child activity [1.2542.1] "Flowchart"`
`10: Activity [1.2542.1] "Flowchart" is Executing`
`14: Activity [1.2542.2] "Wait<IDictionary<String,String>>" is Closed`
`15: Activity [1.2542.1] "Flowchart" is Closed`
`16: Activity [1.2542] "WaitForInitializeInput" is Closed`

Would be cool if you could push me in the right direction. Right now, we cannot access the workflow Host object becaus it is internal.

**Comment by macgyver2k** [comment]
I just found there is already a tracking Provider that writes to `ActivityActorEventSource` 

[https://github.com/wasabii/Cogito.ServiceFabric/blob/master/Cogito.ServiceFabric.Activities/ActivityActorEventSource.cs](url)

The second eye opener is the fact, that i can easily add a custom TrackingParticipant by providing it as WorkflowExtension.

**Comment by wasabii** [comment]
Ahh, yup. Glad you found those!
